name: streamlit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - pip:
    - streamlit==1.39.0
    - plotly==5.23.0
    - pandas==2.1.4
    - sqlalchemy==2.0.25
    - psycopg2-binary==2.9.9
